-- MySQL Script generated by MySQL Workbench
-- Tue Dec 18 23:10:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema supehatr_bawtdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supehatr_bawtdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supehatr_bawtdb` DEFAULT CHARACTER SET utf8 ;
USE `supehatr_bawtdb` ;

-- -----------------------------------------------------
-- Table `supehatr_bawtdb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supehatr_bawtdb`.`User` (
  `idUser` INT NOT NULL,
  `avatarURL` VARCHAR(256) NULL,
  `bot` TINYINT NULL,
  `username` VARCHAR(128) NULL,
  `tag` VARCHAR(128) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supehatr_bawtdb`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supehatr_bawtdb`.`Message` (
  `idMessage` INT NOT NULL,
  `author` INT NOT NULL,
  `channel` INT NOT NULL,
  `content` TEXT(2000) NOT NULL,
  `createdAt` DATE NOT NULL,
  PRIMARY KEY (`idMessage`),
  INDEX `author_idx` (`author` ASC) VISIBLE,
  CONSTRAINT `author`
    FOREIGN KEY (`author`)
    REFERENCES `supehatr_bawtdb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
